/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/queries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listQueries"];
        put?: never;
        post: operations["createQuery"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Health: {
            /** @enum {string} */
            status: "ok";
        };
        CreateQueryRequest: {
            name: string;
            organization?: string;
            /** Format: email */
            email: string;
            requirements: string;
        };
        CreateQueryResponse: {
            id: string;
            /** Format: date-time */
            createdAt: string;
        };
        /** @enum {string} */
        QueryStatus: "NEW" | "IN_PROGRESS" | "RESOLVED";
        Query: {
            id: string;
            name: string;
            organization: string | null;
            /** Format: email */
            email: string;
            requirements: string;
            status: components["schemas"]["QueryStatus"];
            /** Format: date-time */
            createdAt: string;
        };
        ErrorResponse: {
            error: {
                code: string;
                message: string;
                details?: unknown;
            };
        };
    };
    responses: {
        /** @description Error */
        Error: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service is healthy */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    listQueries: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All queries */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Query"][];
                };
            };
            401: components["responses"]["Error"];
            500: components["responses"]["Error"];
        };
    };
    createQuery: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateQueryRequest"];
            };
        };
        responses: {
            /** @description Query created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateQueryResponse"];
                };
            };
            400: components["responses"]["Error"];
            429: components["responses"]["Error"];
            500: components["responses"]["Error"];
        };
    };
}
